# This policy opens port 10250 for VPN communication between master and workers, the DNS port
# (53), port 2049 for communication with NFS file servers, and ports 443 and 3260 for communication
# to block storage.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-ibm-ports-private
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 53
      - 2049
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
      - 2049
      - 3260
      - 443
    protocol: TCP
    source: {}
  ingress:
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_private'
  types:
  - Ingress
  - Egress